package com.accor.asa.interfaces.domain.account.siebel.CustomUI;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2015-08-04T11:39:18.231+02:00
 * Generated source version: 2.5.10
 * 
 */
@WebServiceClient(name = "ACCOR_spcAccount_spcSet_spcAccess_spcCode", 
                  wsdlLocation = "file:../../config/properties/services-echanges/mdm/ANAIS-INT14-MDM-ACCESS.wsdl",
                  targetNamespace = "http://siebel.com/CustomUI") 
public class ACCORSpcAccountSpcSetSpcAccessSpcCode_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://siebel.com/CustomUI", "ACCOR_spcAccount_spcSet_spcAccess_spcCode");
    public final static QName ACCORSpcAccountSpcSetSpcAccessSpcCode = new QName("http://siebel.com/CustomUI", "ACCOR_spcAccount_spcSet_spcAccess_spcCode");
    static {
        URL url = null;
        try {
            url = new URL("file:../../config/properties/services-echanges/mdm/ANAIS-INT14-MDM-ACCESS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ACCORSpcAccountSpcSetSpcAccessSpcCode_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:../../config/properties/services-echanges/mdm/ANAIS-INT14-MDM-ACCESS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ACCORSpcAccountSpcSetSpcAccessSpcCode_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ACCORSpcAccountSpcSetSpcAccessSpcCode_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ACCORSpcAccountSpcSetSpcAccessSpcCode_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ACCORSpcAccountSpcSetSpcAccessSpcCode
     */
    @WebEndpoint(name = "ACCOR_spcAccount_spcSet_spcAccess_spcCode")
    public ACCORSpcAccountSpcSetSpcAccessSpcCode getACCORSpcAccountSpcSetSpcAccessSpcCode() {
        return super.getPort(ACCORSpcAccountSpcSetSpcAccessSpcCode, ACCORSpcAccountSpcSetSpcAccessSpcCode.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ACCORSpcAccountSpcSetSpcAccessSpcCode
     */
    @WebEndpoint(name = "ACCOR_spcAccount_spcSet_spcAccess_spcCode")
    public ACCORSpcAccountSpcSetSpcAccessSpcCode getACCORSpcAccountSpcSetSpcAccessSpcCode(WebServiceFeature... features) {
        return super.getPort(ACCORSpcAccountSpcSetSpcAccessSpcCode, ACCORSpcAccountSpcSetSpcAccessSpcCode.class, features);
    }

}
