
package com.accor.asa.interfaces.domain.account.siebel.CustomUI;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2015-08-04T11:39:18.063+02:00
 * Generated source version: 2.5.10
 * 
 */
public final class ACCORSpcAccountSpcSetSpcAccessSpcCode_ACCORSpcAccountSpcSetSpcAccessSpcCode_Client {

    private static final QName SERVICE_NAME = new QName("http://siebel.com/CustomUI", "ACCOR_spcAccount_spcSet_spcAccess_spcCode");

    private ACCORSpcAccountSpcSetSpcAccessSpcCode_ACCORSpcAccountSpcSetSpcAccessSpcCode_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ACCORSpcAccountSpcSetSpcAccessSpcCode_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ACCORSpcAccountSpcSetSpcAccessSpcCode_Service ss = new ACCORSpcAccountSpcSetSpcAccessSpcCode_Service(wsdlURL, SERVICE_NAME);
        ACCORSpcAccountSpcSetSpcAccessSpcCode port = ss.getACCORSpcAccountSpcSetSpcAccessSpcCode();  
        
        {
        System.out.println("Invoking accorSpcAccountSpcSetSpcAccessSpcCode...");
        com.accor.asa.interfaces.domain.account.siebel.CustomUI.ACCORSpcAccountSpcSetSpcAccessSpcCodeInput _accorSpcAccountSpcSetSpcAccessSpcCode_accorSpcAccountSpcSetSpcAccessSpcCodeInput = new com.accor.asa.interfaces.domain.account.siebel.CustomUI.ACCORSpcAccountSpcSetSpcAccessSpcCodeInput();
        com.accor.asa.interfaces.domain.account.siebel.CustomUI.ACCORSpcAccountSpcSetSpcAccessSpcCodeOutput _accorSpcAccountSpcSetSpcAccessSpcCode__return = port.accorSpcAccountSpcSetSpcAccessSpcCode(_accorSpcAccountSpcSetSpcAccessSpcCode_accorSpcAccountSpcSetSpcAccessSpcCodeInput);
        System.out.println("accorSpcAccountSpcSetSpcAccessSpcCode.result=" + _accorSpcAccountSpcSetSpcAccessSpcCode__return);


        }

        System.exit(0);
    }

}
