package com.accor.asa.interfaces.domain.account.siebel.CustomUI;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2015-08-04T11:39:18.213+02:00
 * Generated source version: 2.5.10
 * 
 */
@WebService(targetNamespace = "http://siebel.com/CustomUI", name = "ACCOR_spcAccount_spcSet_spcAccess_spcCode")
@XmlSeeAlso({com.accor.asa.interfaces.domain.account.siebel.xml.swiorganizationacio.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ACCORSpcAccountSpcSetSpcAccessSpcCode {

    @WebResult(name = "ACCOR_spcAccount_spcSet_spcAccess_spcCode_Output", targetNamespace = "http://siebel.com/CustomUI", partName = "ACCOR_spcAccount_spcSet_spcAccess_spcCode_Output")
    @WebMethod(operationName = "ACCOR_spcAccount_spcSet_spcAccess_spcCode", action = "document/http://siebel.com/CustomUI:ACCOR_spcAccount_spcSet_spcAccess_spcCode")
    public ACCORSpcAccountSpcSetSpcAccessSpcCodeOutput accorSpcAccountSpcSetSpcAccessSpcCode(
        @WebParam(partName = "ACCOR_spcAccount_spcSet_spcAccess_spcCode_Input", name = "ACCOR_spcAccount_spcSet_spcAccess_spcCode_Input", targetNamespace = "http://siebel.com/CustomUI")
        ACCORSpcAccountSpcSetSpcAccessSpcCodeInput accorSpcAccountSpcSetSpcAccessSpcCodeInput
    );
}
