package com.accor.interfaces.domain.account.siebel.CustomUI;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.10
 * 2016-01-11T11:07:55.356+01:00
 * Generated source version: 2.5.10
 * 
 */
@WebServiceClient(name = "OrganizationServiceB2BV5", 
                  wsdlLocation = "file:../../config/properties/services-echanges/mdm/ANAIS-INT10-accountV5-MDM.wsdl",
                  targetNamespace = "http://siebel.com/CustomUI") 
public class OrganizationServiceB2BV5 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://siebel.com/CustomUI", "OrganizationServiceB2BV5");
    public final static QName UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5 = new QName("http://siebel.com/CustomUI", "UCM_spcOrganization_spcCustomer_spcProfile_spcIntegration_spcSOAP_spcProcess_spcB2B_spcV5");
    static {
        URL url = null;
        try {
            url = new URL("file:../../config/properties/services-echanges/mdm/ANAIS-INT10-accountV5-MDM.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrganizationServiceB2BV5.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:../../config/properties/services-echanges/mdm/ANAIS-INT10-accountV5-MDM.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrganizationServiceB2BV5(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrganizationServiceB2BV5(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrganizationServiceB2BV5() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5
     */
    @WebEndpoint(name = "UCM_spcOrganization_spcCustomer_spcProfile_spcIntegration_spcSOAP_spcProcess_spcB2B_spcV5")
    public UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5 getUCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5() {
        return super.getPort(UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5, UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5
     */
    @WebEndpoint(name = "UCM_spcOrganization_spcCustomer_spcProfile_spcIntegration_spcSOAP_spcProcess_spcB2B_spcV5")
    public UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5 getUCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5(WebServiceFeature... features) {
        return super.getPort(UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5, UCMSpcOrganizationSpcCustomerSpcProfileSpcIntegrationSpcSOAPSpcProcessSpcB2BSpcV5.class, features);
    }

}
